# generate root apps for each environment
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  generators:
    # https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Cluster
    - clusters:
        selector:
          matchLabels:
            provider: vcluster
  template:
    metadata:
      # [] notation is not supported in templating
      # (e.g. {{metadata.labels["environment"]}} )
      name: app-of-apps-{{metadata.labels.environment}}
      namespace: argocd
    spec:
      project: homelab
      source:
        repoURL: https://github.com/erhhung/argocd-test.git
        targetRevision: main
        path: root-helmfile
        # https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins#using-environment-variables-in-your-plugin
        plugin:
          name: helmfile
          # HELMFILE_FILE
          # HELMFILE_ENVIRONMENT
          # HELMFILE_RELEASE_NAME
          # HELMFILE_SELECTOR
          env:
            - name: HELMFILE_ENVIRONMENT
              value: '{{metadata.labels.environment}}'
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
        # https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options
        syncOptions:
          - ApplyOutOfSyncOnly=true
