# generate test apps for each Helm chart
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Values.env }}-apps
  namespace: argocd
spec:
  generators:
    # https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Git/
    - git:
        repoURL: https://github.com/erhhung/argocd-test.git
        revision: main
        directories:
          - path: app-charts/*
  template:
    metadata:
      # {\{ ... }\} with    space padding is Helm    templating
      # {\{...}\}   without space padding is Argo CD templating
      name: {{ .Values.env }}-{{ "{{path.basename}}" }}
      namespace: argocd
    spec:
      project: homelab
      source:
        repoURL: {{ .Values.source.repoURL }}
        targetRevision: {{ .Values.source.targetRevision }}
        path: app-charts/{{ "{{path.basename}}" }}
        helm:
          valueFiles:
            - /app-values/{{ "{{path.basename}}" }}/values-{{ .Values.env }}.yaml
          ignoreMissingValueFiles: true
      destination:
        name: {{ .Values.destination.name }}
        namespace: {{ .Values.destination.namespace }}
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
